name: Create Tag and Release on Deploy

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  create_tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: environment setup
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "Setting environment to Production"
            echo "ENVIRONMENT=preprod" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "Setting environment to Development"
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "Setting environment to Default"
            echo "ENVIRONMENT=default" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Application
        run: |
          npm run build

      - name: Deploy to Preprod
        run: |
          echo "Deploying to Preprod..."

      - name: Get short commit hash
        id: git_short_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      # Create a new tag based on the commit SHA
      - name: Create Tag
        id: create_tag
        run: |
          git tag v${{ steps.git_short_hash.outputs.hash }}
          git push origin v${{ steps.git_short_hash.outputs.hash }}

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v${{ steps.git_short_hash.outputs.hash }}
          release_name: Release v${{ steps.git_short_hash.outputs.hash }}
          body: |
            Release created automatically by GitHub Actions.
          draft: false
          prerelease: ${{ env.prerelease }}