# .github/workflows/deploy.yml
name: Deploy gh-pages to FTP (DOGADO)

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to FTP Server
        # NEueste Version: https://github.com/SamKirkland/FTP-Deploy-Action/releases
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Wurzelverzeichnis des gh-pages Branches
          server-dir: /sv-zogenweiler.de  # ggf. anpassen, z. B. /www oder leer lassen
